### ISSUE TITLE
Can't sync the testnet.

### ISSUE THREAD

**Issue by peipeitu** [seredat/karbowanec#83]
Is there any testnet peer? I want the testnet blockchain for pool testing.

**Comment by aivve** [comment]
There is testnet where your pool will be obsolete 😁 as well as others, at least until someone bothers to make new pool software https://github.com/Karbovanets/papers/blob/master/KIP-001.md

**Comment by peipeitu** [comment]
@aivve Thanks! It worked! There is another problem occured...
When I start to mine for my pool, I just got 'Failed to parse block.'
I know that it is something wrong with the package 'node-cryptonote-util'. Is there any special package for karbo?

**Comment by peipeitu** [comment]
However, I have tried the package https://github.com/aivve/node-cryptonote-util.git.
But failed.
```
  CXX(target) Release/obj.target/cryptonote/src/cryptonote_core/cryptonote_format_utils.o
  CC(target) Release/obj.target/cryptonote/src/crypto/tree-hash.o
  CXX(target) Release/obj.target/cryptonote/src/crypto/crypto.o
../src/crypto/crypto.cpp: In function 'std::size_t crypto::rs_comm_size(std::size_t)':
../src/crypto/crypto.cpp:224:58: error: value-initialization of incomplete type 'crypto::rs_comm::<unnamed struct> []'
     return sizeof(rs_comm) + pubs_count * sizeof(rs_comm().ab[0]);
                                                          ^
cryptonote.target.mk:121: recipe for target 'Release/obj.target/cryptonote/src/crypto/crypto.o' failed
make: *** [Release/obj.target/cryptonote/src/crypto/crypto.o] Error 1
make: Leaving directory '/root/xmr-stratum/node_modules/forknote-util/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.14.116-boot2docker
gyp ERR! command "/root/node/bin/node" "/root/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/xmr-stratum/node_modules/forknote-util
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! forknote-util@0.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the forknote-util@0.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
